### PR TITLE
WIP Viz Prototype Page

### PR DESCRIPTION
**Pull request by lukad03**
Setting up the styles and foundational elements before building the prototype.

* Remove Merriweather font
* Add Roboto Font (Census font)
* Add Census brand colors
* Create styleguide layout
* Add Viz Type Sidenav
* Update grid styles

### CODE REVIEW

**Comment by lukad03** [comment]
@s2t2 I'm likely going to continue working on this tomorrow morning, so feel free to drop in feedback whenever you get the chance.

**Comment by s2t2** [comment]
@lukad03 Oh ok, just seeing this now. I will pull this down and take a look later tonight.

**Comment by s2t2** [comment]
#### Interface/Integration Review

Header is looking good. Love seeing the blank page. Its inviting us to develop it :-)

screen shot 2017-11-15 at 12 41 05 am


Here's how you know!

screen shot 2017-11-15 at 12 41 25 am


When testing responsivity to browser width resizing, I noticed some potential areas for further refinement: namely, the visibility of the site title and the flag 🇺🇸 

screen shot 2017-11-15 at 12 40 51 am

**Comment by s2t2** [comment]
#### Branding and Identity Review

I notice the nav background color (`#112E51`) is a USWDS color as well as a Census color. Whereas the menu button background color (`#0071bc`) is a USWDS color but not a Census color (the corresponding Census color would be `#205493`). So the color choices so far reflect a USWDS identity. Then I notice `Roboto` font with `Helvetica` and sans-serif fall-backs. The `Roboto` font reflects a Census identity. So I'm noticing an identity conflict within the site. 

To retain a strong site identity, if we want to keep the `Roboto` font, we should adopt a more Census-specific scope and title and color scheme. Otherwise, we should keep the USWDS colors and switch the fonts to USWDS fonts (`Merriweather` & `Source Sans Pro`).

Given the site's more general title ("Data Design Standards") and scope as I understand it (providing guidance for all agencies), perhaps adopting a more general USWDS identity is the preferred approach. 

In that case we could still provide Census-specific branding guidance on one of several agency-specific pages. But that begs the question, is it the role of the Data Design Standards project to house and keep updated the branding guidance for all federal agencies? That might be a more applicable role for the agencies themselves, or maybe even USWDS, but probably not for Data Design Standards. 

Executive Summary Final Recommendations:

  + This site should adhere strictly to USWDS branding and identity without any consideration for agency-specific branding, and the same goes for all of this site's example data visualizations and the future code library project.
  + If there is a need to provide Census-specific branding and identity guidance, it should be done in a separate site.

**Comment by lukad03** [comment]
@s2t2 Need to merge this in but we can review this post-meeting

**Pull request merged**
